name: flowery_tts
version: 1.3.0
description: >-
  An unofficial wrapper for the Flowery TTS API, offering
  over 1000 Text-to-Speech voices with translation support.

repository: https://github.com/priyanuj-gogoi/flowery-tts

environment:
  sdk: ^3.0.0

platforms:
  android:
  ios:
  linux:
  macos:
  windows:
  web:

topics:
  - api-wrapper
  - text-to-speech
  - tts

dependencies:
  http: ^1.0.0
  meta: ^1.12.0
